"use client";

import { useMemo, useState } from "react";
import ArchitectureViz from "../components/ArchitectureViz";
import { compareMemory } from "../lib/memory";

const chapters = [["motivation","Why change"],["map","Model map"],["cache","KV cache"],["plastic","Plasticity"],["hebbian","Hebbian rule"],["bdh","Dragon Hatchling"],["compare","Compare"]];

export default function Page() {
  const [context, setContext] = useState(8); const [repetitions, setRepetitions] = useState(2); const [plasticity, setPlasticity] = useState(.35); const [retention, setRetention] = useState(.9);
  const state = useMemo(() => compareMemory({ contextLength: context, repetitions, plasticity, decay: retention }), [context, repetitions, plasticity, retention]);
  return <>
    <nav aria-label="Chapters">{chapters.map(([id,text])=><a key={id} href={`#${id}`}><i />{text}</a>)}</nav>
    <main className="article-main"><article>
      <header id="motivation"><time>September 8, 2026</time><h1>Can a network remember by changing itself?</h1><p className="lead">Start with a familiar small language model. Then change one part at a time until recent experience lives inside the network.</p></header>
      <section id="map"><span className="number">01</span><h2>First, see the whole machine</h2><p>A language model receives tokens at the bottom and passes them through a stack of processing blocks. Each block transforms the current representation. The final layer converts it into scores for the next token.</p><p>The left tower is a teaching-scale nano-GPT. The right tower keeps the same readable scaffold but adds a changing internal state. This hybrid is our bridge to the biological idea. It is not the full Dragon Hatchling architecture.</p><ArchitectureViz mode="overview" value={state.trace} label="Nano-GPT beside the plastic-memory teaching model" /><p className="annotation"><b>What to notice:</b> the ordinary model stores its learned behavior in fixed parameters. The hybrid has a second, temporary state that can change during use.</p></section>
      <section id="cache"><span className="number">02</span><h2>GPT remembers by keeping earlier token records</h2><p>During generation, a Transformer saves information derived from every earlier token. These saved entries are called keys and values, so the store is called a <strong>KV cache</strong>.</p><p>The cache is outside the model’s trained weights. Add more context and more rows must remain available. Move the slider to make that growth visible.</p><ArchitectureViz mode="kv" value={context / 24} label="A nano-GPT block writing key and value rows" /><Control label="Tokens kept in context" value={context} min={2} max={24} step={1} set={setContext} /><p className="annotation"><b>{context} token records.</b> Longer context preserves more separate entries, but the working store grows with the sequence.</p></section>
      <section id="plastic"><span className="number">03</span><h2>Plastic means a connection can change</h2><p>A synapse is the junction where one neuron influences another. The strength of that influence is not always fixed. Recent activity can make the next signal stronger or weaker. That ability to change is called <strong>synaptic plasticity</strong>.</p><p>For an artificial network, imagine each line between two units has a temporary strength written on it. Repeated activity can change the line without retraining every permanent model parameter.</p><ArchitectureViz mode="hebbian" value={state.trace} label="One active input and output strengthening their shared connection" /><Control label="Repeat the same experience" value={repetitions} min={0} max={6} step={1} set={setRepetitions} /><p className="annotation">After {repetitions} compatible experience{repetitions===1?"":"s"}, the temporary trace is <b>{Math.round(state.trace*100)}%</b> strong.</p></section>
      <section id="hebbian"><span className="number">04</span><h2>The Hebbian rule says which connection changes</h2><p>“Hebbian” is just the name of the update rule. If an input unit and an output unit are active together, the cell connecting that pair receives a mark. All possible pairs form a table called the <strong>Hebbian matrix</strong>.</p><div className="equation"><span>new memory</span><b>=</b><span>faded old memory</span><b>+</b><span>plasticity × input × output</span></div><p>The plasticity factor controls the size of the new mark. Retention controls how much of the old mark survives. They answer two ordinary questions: “How quickly should I learn this?” and “How quickly should I forget it?”</p><div className="control-pair"><Control label="Plasticity factor" value={plasticity} min={0} max={1} step={.05} set={setPlasticity}/><Control label="Retention" value={retention} min={.5} max={1} step={.05} set={setRetention}/></div></section>
      <section id="bdh"><span className="number">05</span><h2>Dragon Hatchling turns this idea into an architecture</h2><p>The published Dragon Hatchling model goes beyond adding one matrix to GPT. It describes a scale-free network of locally interacting neuron particles. Activity is sparse and positive. Its brain interpretation uses spikes, while recent working memory is carried by changing synaptic connections.</p><p>The diagram below changes visual language on purpose. A Transformer is a regular stack. The BDH idea is a graph with local neighborhoods, hub-like neurons, and selected connections whose state changes during inference.</p><ArchitectureViz mode="bdh" value={state.trace} label="Teaching-scale view of locally interacting BDH-style neuron particles" /><p className="annotation"><b>Evidence boundary:</b> this scene explains architectural ideas from the paper. It does not load trained BDH weights or reproduce a benchmark.</p></section>
      <section id="compare"><span className="number">06</span><h2>Now compare the memory, not just the shape</h2><div className="comparison"><div><small>NANO-GPT</small><h3>Keep token-derived records</h3><strong>{state.kvSlots}</strong><span>KV slots in this example</span></div><div><small>PLASTIC HYBRID</small><h3>Change a fixed state in place</h3><strong>{state.plasticSlots}</strong><span>cells in the teaching matrix</span></div></div><p>The comparison is not “one is always better.” A KV cache preserves distinct token records. A fixed plastic state has a stable footprint, but new memories may interfere with old ones. The useful research question is when rapid in-network adaptation is worth that trade-off.</p><p className="sources"><a href="https://arxiv.org/abs/2509.26507">Dragon Hatchling paper</a> · <a href="https://github.com/pathwaycom/bdh">Official BDH implementation</a> · <a href="https://github.com/bbycroft/llm-viz">Bycroft model-visualization source</a></p></section>
    </article></main>
  </>;
}

function Control({label,value,min,max,step,set}) { return <label className="single-control"><span>{label}</span><output>{step<1?Number(value).toFixed(2):value}</output><input aria-label={label} type="range" min={min} max={max} step={step} value={value} onChange={e=>set(Number(e.target.value))}/></label>; }

