"use client";
import {useEffect,useMemo,useState} from "react";
import NanoGptWebGL from "./NanoGptWebGL";
const CODES=["LUMEN","EMBER","NOVA","CIRRUS"],clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const score=(eta,retention,delay,interference)=>clamp(.12+.92*eta*Math.pow(retention,delay)/(1+.42*interference),.125,.98);
export const modelSections=[
 {id:"model-task",number:"2.1",title:"A delayed access-code task"},{id:"model-baseline",number:"2.2",title:"Execute the frozen model"},{id:"model-kv",number:"2.3",title:"KV cache preserves every token"},{id:"model-write",number:"2.4",title:"Write an association into fast weights"},{id:"model-recall",number:"2.5",title:"Read the memory inside the frozen pass"},{id:"model-benchmark",number:"2.6",title:"Benchmark all three memory conditions"},{id:"model-boundary",number:"2.7",title:"What is measured and what remains to validate"}
];

export default function ModelChapter(){
 const [variant,setVariant]=useState("plastic"),[eta,setEta]=useState(.55),[retention,setRetention]=useState(.9),[delay,setDelay]=useState(4),[interference,setInterference]=useState(1),[step,setStep]=useState(0),[running,setRunning]=useState(false);
 useEffect(()=>{if(!running)return;const timer=setInterval(()=>setStep(s=>s>=5?(setRunning(false),5):s+1),700);return()=>clearInterval(timer)},[running]);
 const recall=score(eta,retention,delay,interference);
 return <>
  <section id="model-task"><N n="2.1" title="A delayed access-code task"/><p>The experiment gives one frozen model a new fact, inserts unrelated tokens, and later asks for that fact. The learned parameters are identical in every condition. Only the temporary state changes.</p><div className="sequence-strip"><span>write</span><b>Sector K → LUMEN</b><i/><span>delay</span><b>{delay} distractor steps</b><i/><span>query</span><b>Sector K → ?</b></div><Control label="Delay before recall" value={delay} min={0} max={12} step={1} set={setDelay} suffix=" steps"/></section>
  <section id="model-baseline"><N n="2.2" title="Execute the frozen model"/><p>This expanded transformer view exposes the tensor operations instead of reducing the model to a stack of boxes. Select a memory condition, click a labeled tensor, or scrub the execution. The arrows and matrix workbench show what the active stage calculates.</p><VariantTabs value={variant} set={setVariant}/><FrozenModel variant={variant} eta={eta} setEta={setEta} retention={retention} step={step} setStep={v=>{setRunning(false);setStep(v)}}/><div className="execution-controls"><button onClick={()=>{setStep(0);setRunning(true)}}>{running?"Running…":"Run execution"}</button><Control label="Execution step" value={step} min={0} max={5} step={1} set={v=>{setRunning(false);setStep(v)}}/></div><CellMath step={step} eta={eta} retention={retention}/></section>
  <section id="model-kv"><N n="2.3" title="KV cache preserves every token"/><p>The visualizer’s nanoGPT teaching model has 3 layers, 3 attention heads and a 48-value embedding. In fp32, each retained token adds 1,152 bytes of key and value state. This route recalls accurately, but storage and memory traffic still grow with every retained token.</p><div className="cost-equation"><span>2 tensors</span><b>×</b><span>3 layers</span><b>×</b><span>3 heads</span><b>×</b><span>16 values</span><b>×</b><span>4 bytes</span><strong>1.125 KiB / token</strong></div></section>
  <section id="model-write"><N n="2.4" title="Write an association into fast weights"/><p>The cue projection k and answer projection v form the update ηvkᵀ. The vector field below shows the action of that matrix over a two-dimensional slice of query space. Each arrow is the temporary correction Fq that would be sent back into the frozen residual stream.</p><FastField eta={eta}/><div className="model-control-grid"><Control label="Hebbian plasticity η" value={eta} min={0} max={1} step={.05} set={setEta}/><Control label="Retention λ" value={retention} min={.5} max={1} step={.01} set={setRetention}/></div></section>
  <section id="model-recall"><N n="2.5" title="Read the memory inside the frozen pass"/><p>At the query token, the model calculates q, reads Fq, and adds that result before the frozen output head. Adjusting plasticity above changes the matrix inside this same execution, not a detached chart.</p><RecallMath eta={eta} retention={retention} delay={delay} recall={recall}/><Logits recall={recall}/></section>
  <section id="model-benchmark"><N n="2.6" title="Benchmark all three memory conditions"/><p>The three lines use the same delay axis. No-memory stays at chance. KV cache stays exact while its storage grows. Plastic memory decays smoothly and is also reduced by competing writes.</p><Benchmark eta={eta} retention={retention} interference={interference} delay={delay}/><Control label="Competing writes" value={interference} min={0} max={5} step={1} set={setInterference}/><div className="benchmark-table"><Metric name="No memory" value="12.5%" note="chance over eight codes"/><Metric name="KV cache" value="100%" note="tokens retained exactly"/><Metric name="Plastic state" value={Math.round(recall*100)+"%"} note="current interactive setting"/></div></section>
  <section id="model-boundary"><N n="2.7" title="What is measured and what remains to validate"/><p className="article-note">Evidence boundary: the frozen path uses the public three-layer nanoGPT configuration and an exact small matrix walkthrough of our adapter. We have not yet inserted the adapter into the visualizer’s pretrained sort-model checkpoint. That end-to-end checkpoint integration and its token likelihoods remain the next experimental milestone.</p><p className="sources">Frozen host: bbycroft/llm-viz gpt-nano sort model, 3 layers, 3 heads, 48-value embedding. Tensor-block layout and walkthrough interaction adapted from Brendan Bycroft’s LLM Visualization, whose package metadata declares MIT.</p></section>
 </>;
}

const stages=["token embedding","attention projection","frozen MLP","fast-memory read","residual addition","output logits"];
function FrozenModel({variant,eta,setEta,retention,step,setStep}){return <><NanoGptWebGL variant={variant} eta={eta} setEta={setEta} retention={retention} step={step} setStep={setStep}/><ol className="execution-timeline webgl-timeline">{stages.map((s,i)=><li key={s} className={i===step?"active":i<step?"done":""}>{i+1}<span>{s}</span></li>)}</ol></>}
function CellMath({step,eta,retention}){const rows=[["lookup","x = E[token]","x = [0.80, 0.10, 0.60, 0.20]"],["projection","q = Wq x","q₀ = 0.6×0.8 + 0.2×0.1 − 0.1×0.6 + 0.3×0.2 = 0.50"],["nonlinearity","h = GELU(W₂x)","h₀ = GELU(0.73) = 0.56"],["memory read","r = Fq","r₀ = Σⱼ F₀ⱼqⱼ = "+(eta*.5).toFixed(2)],["residual","z = h + λr","z₀ = 0.56 + "+retention.toFixed(2)+"×"+(eta*.5).toFixed(2)+" = "+(.56+retention*eta*.5).toFixed(2)],["logits","ℓ = Wout z","ℓLUMEN = 0.18 + memory evidence"]][step];return <div className="cell-math"><span>{rows[0]}</span><b>{rows[1]}</b><code>{rows[2]}</code></div>}
function FastField({eta}){const sx=v=>360+v*135,sy=v=>170-v*135,arrows=[];for(let y=-1;y<=1;y+=.25)for(let x=-1;x<=1;x+=.25){const dot=.8*x+.25*y,dx=eta*dot*.25,dy=eta*dot*.8,m=Math.hypot(dx,dy)||1;arrows.push({x,y,dx:dx/m*12*eta,dy:dy/m*12*eta})}return <svg className="fast-field" viewBox="0 0 720 340" role="img" aria-label="Fast-weight vector field mapping query directions toward the LUMEN value"><defs><marker id="fast-arrow" viewBox="0 0 8 8" refX="7" refY="4" markerWidth="5" markerHeight="5" orient="auto"><path d="M0 0L8 4L0 8Z"/></marker></defs><line className="axis" x1="210" y1="170" x2="510" y2="170"/><line className="axis" x1="360" y1="20" x2="360" y2="320"/>{arrows.map((a,i)=><line key={i} x1={sx(a.x)-a.dx/2} y1={sy(a.y)+a.dy/2} x2={sx(a.x)+a.dx/2} y2={sy(a.y)-a.dy/2} opacity={.18+.55*eta} markerEnd="url(#fast-arrow)"/>)}<circle cx={sx(.8)} cy={sy(.25)} r="6"/><text x={sx(.8)+10} y={sy(.25)-8}>q · Sector K</text><line className="query-read" x1={sx(.8)} y1={sy(.25)} x2={sx(.8)+eta*34} y2={sy(.25)-eta*108} markerEnd="url(#fast-arrow)"/><text x="28" y="35">Fq points toward the stored value</text><text x="28" y="55">arrow length follows η</text></svg>}
function RecallMath({eta,retention,delay,recall}){const trace=eta*Math.pow(retention,delay);return <div className="recall-math"><div><span>surviving trace</span><b>ηλᵈ = {eta.toFixed(2)} × {retention.toFixed(2)}<sup>{delay}</sup></b><strong>{trace.toFixed(3)}</strong></div><div><span>retrieval</span><b>r = Fq</b><strong>{(trace*.82).toFixed(3)}</strong></div><div><span>final evidence</span><b>frozen logit + r</b><strong>{recall.toFixed(3)}</strong></div></div>}
function Logits({recall}){return <div className="logit-bars">{[["LUMEN",recall],["EMBER",.34*(1-recall)],["NOVA",.24*(1-recall)],["ATLAS",.18*(1-recall)]].map(([n,v])=><div key={n}><span>{n}</span><i style={{width:(v*100)+"%"}}/><b>{v.toFixed(2)}</b></div>)}</div>}
function Benchmark({eta,retention,interference,delay}){const W=720,H=310,x=v=>55+v/12*630,y=v=>25+(1-v)*225,series=[{n:"No memory",c:"a",p:Array.from({length:13},(_,d)=>[d,.125])},{n:"KV cache",c:"b",p:Array.from({length:13},(_,d)=>[d,1])},{n:"Plastic state",c:"c",p:Array.from({length:13},(_,d)=>[d,score(eta,retention,d,interference)])}],path=p=>p.map((q,i)=>(i?"L":"M")+x(q[0])+","+y(q[1])).join(" ");return <figure className="benchmark-chart"><figcaption>Exact recall across delay</figcaption><svg viewBox={"0 0 "+W+" "+H}>{[0,.25,.5,.75,1].map(v=><g key={v}><line className="grid" x1="55" y1={y(v)} x2="685" y2={y(v)}/><text x="45" y={y(v)+4} textAnchor="end">{Math.round(v*100)}%</text></g>)}{series.map(s=><path key={s.n} className={"series-"+s.c} d={path(s.p)}/>)}<line className="delay-marker" x1={x(delay)} y1="25" x2={x(delay)} y2={y(0)}/><text x={x(delay)+5} y="42">current delay</text><text x="370" y="298" textAnchor="middle">distractor steps</text></svg><div className="chart-legend">{series.map(s=><span key={s.n}><i className={s.c}/>{s.n}</span>)}</div></figure>}
function VariantTabs({value,set}){return <div className="variant-tabs" role="tablist">{[["base","No memory"],["kv","KV cache"],["plastic","Fast weights"]].map(([id,label])=><button key={id} role="tab" aria-selected={value===id} onClick={()=>set(id)}>{label}</button>)}</div>}
function Control({label,value,min,max,step,set,suffix=""}){return <label className="model-control"><span>{label}<output>{step<1?value.toFixed(2):value}{suffix}</output></span><input type="range" aria-label={label} min={min} max={max} step={step} value={value} onChange={e=>set(Number(e.target.value))}/></label>}
function Metric({name,value,note}){return <div><span>{name}</span><b>{value}</b><small>{note}</small></div>}
function N({n,title}){return <><span className="number">{n}</span><h2>{title}</h2></>}
