const C={bg:"#f1f1f1",ink:"#343434",mid:"#9b9b9b",light:"#d4d4d4",white:"#ececec",pale:"#e7e7e7"};
const clamp=v=>Math.max(0,Math.min(1,v));
function frame(canvas){const d=Math.min(devicePixelRatio||1,2),w=canvas.clientWidth,h=canvas.clientHeight;if(canvas.width!==w*d||canvas.height!==h*d){canvas.width=w*d;canvas.height=h*d}const c=canvas.getContext("2d");c.setTransform(d,0,0,d,0,0);c.clearRect(0,0,w,h);c.lineCap="round";c.lineJoin="round";return{c,w,h}}
function line(c,a,b,color=C.mid,width=1,dash=[]){c.beginPath();c.setLineDash(dash);c.moveTo(...a);c.lineTo(...b);c.strokeStyle=color;c.lineWidth=width;c.stroke();c.setLineDash([])}
function dot(c,x,y,r,color=C.ink){c.beginPath();c.arc(x,y,r,0,Math.PI*2);c.fillStyle=color;c.fill()}
function text(c,s,x,y,size=12,color=C.ink,align="center"){c.fillStyle=color;c.font=`${size}px Lato`;c.textAlign=align;c.fillText(s,x,y)}
function arrow(c,a,b,color=C.ink,width=1.5){line(c,a,b,color,width);const q=Math.atan2(b[1]-a[1],b[0]-a[0]);c.beginPath();c.moveTo(...b);c.lineTo(b[0]-8*Math.cos(q-.42),b[1]-8*Math.sin(q-.42));c.lineTo(b[0]-8*Math.cos(q+.42),b[1]-8*Math.sin(q+.42));c.fillStyle=color;c.fill()}
function axis(c,w,h,xLabel,yLabel){line(c,[70,h-55],[w-45,h-55],C.mid);line(c,[70,h-55],[70,45],C.mid);text(c,xLabel,w-48,h-30,11,C.mid,"right");text(c,yLabel,74,31,11,C.mid,"left")}
const renders={
speeds(c,w,h,v){const n=+v,layers=[[w*.16],[w*.43-42,w*.43,w*.43+42],[w*.7-30,w*.7+30],[w*.88]],ys=[[h*.5],[h*.28,h*.5,h*.72],[h*.38,h*.62],[h*.5]];for(let a=0;a<layers.length-1;a++)for(let i=0;i<layers[a].length;i++)for(let j=0;j<layers[a+1].length;j++){const active=a===1&&i===1&&j===0;line(c,[layers[a][i],ys[a][i]],[layers[a+1][j],ys[a+1][j]],active?C.ink:C.light,active?1.5+n*2.4:1)}for(let a=0;a<layers.length;a++)for(let i=0;i<layers[a].length;i++){const active=(a===1&&i===1)||(a===2&&i===0);dot(c,layers[a][i],ys[a][i],active?10:7,active&&n?C.ink:C.white);c.strokeStyle=C.ink;c.lineWidth=1;c.stroke()}text(c,"input",layers[0][0],h*.84,11,C.mid);text(c,"hidden units",layers[1][1],h*.84,11,C.mid);text(c,"output",layers[2][0],h*.84,11,C.mid);text(c,n?`paired ${n} times`:"no paired activity",w/2,42,13,C.ink)},
write(c,w,h,v){const s=+v,cols=6,rows=5,size=Math.min(48,(w-210)/cols),x0=(w-cols*size)/2,y0=66;for(let r=0;r<rows;r++)for(let k=0;k<cols;k++){const chosen=r===2&&k===3;c.fillStyle=chosen?`rgb(${245-190*s},${245-190*s},${245-190*s})`:C.white;c.fillRect(x0+k*size,y0+r*size,size-3,size-3)}text(c,"cue features",x0-22,y0+rows*size/2,11,C.mid,"right");text(c,"action features",x0+cols*size/2,y0+rows*size+25,11,C.mid);arrow(c,[x0-65,y0+size*2.5],[x0-8,y0+size*2.5],C.ink);text(c,`${Math.round(s*100)}%`,x0+size*3.5,y0+size*2.65,12,s>.55?C.white:C.ink);text(c,"one matrix cell stores the co-activation",w/2,h-35,13,C.ink)},
repeat(c,w,h,v){const n=+v,x0=w*.16,step=w*.17,y=h*.49;line(c,[x0-30,y],[x0+step*4+30,y],C.light,1);for(let i=0;i<5;i++){const x=x0+i*step,s=1-Math.pow(.68,i+1),shown=i<n;dot(c,x-20,y,shown?9:6,shown?C.ink:C.white);c.strokeStyle=C.mid;c.lineWidth=1;c.stroke();dot(c,x+20,y,shown?9:6,shown?C.ink:C.white);c.stroke();line(c,[x-11,y],[x+11,y],shown?C.ink:C.light,shown?1+s*8:1);text(c,String(i+1),x,y+43,11,C.mid);if(shown)text(c,`${Math.round(s*100)}%`,x,y-34,11,C.ink)}text(c,"the same connection after each experience",w/2,44,13,C.mid)},
retain(c,w,h,v){const n=+v;axis(c,w,h,"delay steps","strength");c.beginPath();for(let i=0;i<=10;i++){const x=70+i*(w-125)/10,y=h-55-Math.pow(.86,i)*(h-125);i?c.lineTo(x,y):c.moveTo(x,y)}c.strokeStyle=C.ink;c.lineWidth=3;c.stroke();const x=70+n*(w-125)/10,y=h-55-Math.pow(.86,n)*(h-125);line(c,[x,h-55],[x,y],C.mid,1,[4,5]);dot(c,x,y,8,C.ink);text(c,`${Math.round(Math.pow(.86,n)*100)}% remains`,x,y-20,13,C.ink)},
read(c,w,h,v){const m=+v,center=[w/2,h/2],radius=Math.min(w,h)*.3;for(let i=0;i<48;i++){const q=i/48*Math.PI*2,x=center[0]+Math.cos(q)*radius,y=center[1]+Math.sin(q)*radius,alignment=(Math.cos(q)+1)/2;arrow(c,[x,y],[x+Math.cos(q)*(5+18*alignment),y+Math.sin(q)*(5+18*alignment)],alignment>m?C.light:C.ink,1)}const q=(1-m)*Math.PI-.5*Math.PI,x=center[0]+Math.cos(q)*radius,y=center[1]+Math.sin(q)*radius;dot(c,x,y,9,C.ink);line(c,center,[x,y],C.ink,2);text(c,"stored direction",center[0],center[1]-12,12,C.mid);text(c,m>.61?"match found":"match too weak",center[0],h-28,14,C.ink)},
compete(c,w,h,v){const r=+v,l=1-r,cx=w/2,y=h/2;line(c,[w*.14,y],[w*.86,y],C.light,5);c.fillStyle=C.ink;c.fillRect(w*.14,y-22,(w*.72)*l,44);dot(c,cx,y,6,C.white);text(c,"LEFT EVIDENCE",w*.14,70,11,C.mid,"left");text(c,"RIGHT EVIDENCE",w*.86,70,11,C.mid,"right");text(c,`${Math.round(l*100)}%`,w*.14,95,20,C.ink,"left");text(c,`${Math.round(r*100)}%`,w*.86,95,20,C.ink,"right");text(c,l>r?"recall left":r>l?"recall right":"uncertain",cx,h-55,16,C.ink)},
order(c,w,h,v){const pos=+v,y=h*.48,x0=w*.18,step=w*.16;line(c,[x0,y],[x0+step*4,y],C.mid,2);for(let i=1;i<=5;i++){const x=x0+(i-1)*step,different=i===pos;dot(c,x,y,different?17:13,different?C.ink:C.white);c.strokeStyle=C.ink;c.lineWidth=1;c.stroke();text(c,different?"R":"L",x,y+4,11,different?C.white:C.ink);text(c,`t${i}`,x,y+38,11,C.mid)}arrow(c,[x0,y-75],[x0+step*4,y-75],C.mid);text(c,"time",x0+step*2,y-92,11,C.mid);const influence=.42*Math.pow(.86,5-pos);text(c,`conflicting trace at test: ${Math.round(influence*100)}%`,w/2,h-48,14,C.ink)},
capacity(c,w,h,v){const n=+v,cols=3,rows=3,cell=Math.min(80,(w-210)/3),x0=(w-cell*3)/2,y0=58;for(let i=0;i<9;i++){const x=x0+(i%cols)*cell,y=y0+Math.floor(i/cols)*cell,active=i<n;c.fillStyle=active?C.ink:C.white;c.fillRect(x+3,y+3,cell-7,cell-7);if(active){const crowd=Math.max(0,(n-4)/5);c.fillStyle=`rgba(250,250,250,${.15+crowd*.55})`;c.fillRect(x+3,y+3,cell-7,cell-7)}text(c,String(i+1),x+cell/2,y+cell/2+4,11,active?C.white:C.mid)}text(c,n<5?"distinct cells":n<8?"increasing overlap":"crowded representation",w/2,h-38,14,C.ink)},
noise(c,w,h,v){const n=+v;axis(c,w,h,"cue noise","confidence");const draw=(base,color,dash=[])=>{c.beginPath();for(let i=0;i<=20;i++){const t=i/20,x=70+t*(w-125),y=h-55-clamp(base-t*.68)*(h-125);i?c.lineTo(x,y):c.moveTo(x,y)}c.setLineDash(dash);c.strokeStyle=color;c.lineWidth=3;c.stroke();c.setLineDash([])};draw(.42,C.mid,[6,6]);draw(.88,C.ink);const x=70+n*(w-125);line(c,[x,50],[x,h-55],C.mid,1,[3,5]);dot(c,x,h-55-clamp(.88-n*.68)*(h-125),7,C.ink);text(c,"repeated memory",w*.72,72,12,C.ink);text(c,"single example",w*.72,104,12,C.mid)},
claims(c,w,h,v){const n=+v,labels=["observed here","supported by papers","not tested"],sub=["toy behavior","research mechanism","broad capability"],x0=w*.18,step=w*.32,y=h*.46;line(c,[x0,y],[x0+step*2,y],C.light,2);for(let i=0;i<3;i++){const x=x0+i*step;dot(c,x,y,i===n?18:10,i===n?C.ink:C.mid);text(c,labels[i],x,y+48,13,i===n?C.ink:C.mid);text(c,sub[i],x,y+70,11,C.mid)}text(c,"evidence boundary",w/2,54,13,C.mid)}
};
function update(d){const input=d.querySelector("input"),out=d.querySelector("output"),v=input.value,type=d.dataset.demo;if(["read","compete","noise"].includes(type))out.textContent=`${Math.round(v*100)}%`;else if(type==="write")out.textContent=(+v).toFixed(2);else if(type==="order")out.textContent=`${v} of 5`;else if(type==="claims")out.textContent=["Toy model","Research","Broader claim"][v];else out.textContent=v;const{c,w,h}=frame(d.querySelector("canvas"));renders[type](c,w,h,v)}
const demos=[...document.querySelectorAll(".demo")];demos.forEach(d=>{d.querySelector("input").addEventListener("input",()=>update(d));update(d)});new ResizeObserver(()=>demos.forEach(update)).observe(document.body);
const nav=[...document.querySelectorAll(".chapter-nav a")];const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)nav.forEach(a=>a.classList.toggle("active",a.hash===`#${e.target.id}`))}),{rootMargin:"-40% 0px -50%"});nav.map(a=>document.querySelector(a.hash)).forEach(t=>observer.observe(t));

