const VERTEX=`#version 300 es
in vec2 p;void main(){gl_Position=vec4(p,0.,1.);}`;
const FRAGMENT=`#version 300 es
precision highp float;out vec4 color;uniform vec2 resolution;uniform float leftStrength;uniform float rightStrength;
float segment(vec2 p,vec2 a,vec2 b){vec2 pa=p-a,ba=b-a;float h=clamp(dot(pa,ba)/dot(ba,ba),0.,1.);return length(pa-ba*h);}
float circle(vec2 p,vec2 c,float r){return length(p-c)-r;}
void main(){vec2 uv=(gl_FragCoord.xy/resolution.xy)*2.-1.;uv.x*=resolution.x/resolution.y;
float aspect=resolution.x/resolution.y;vec2 cue=vec2(-aspect*.72,0.),mem=vec2(0.,0.),a=vec2(aspect*.72,.48),b=vec2(aspect*.72,-.48);
float l1=segment(uv,cue,mem),l2=segment(uv,mem,a),r2=segment(uv,mem,b);vec3 bg=vec3(.969,.969,.957);vec3 ink=vec3(.55,.56,.54);vec3 teal=vec3(.204,.498,.463);vec3 plum=vec3(.502,.376,.467);vec3 c=bg;
float base=smoothstep(.012,.006,l1);c=mix(c,ink,base*.42);float lp=smoothstep(.018+.018*leftStrength,.006,l2);float rp=smoothstep(.018+.018*rightStrength,.006,r2);c=mix(c,teal,lp*(.18+.82*leftStrength));c=mix(c,plum,rp*(.18+.82*rightStrength));
float n=min(min(circle(uv,cue,.055),circle(uv,mem,.072)),min(circle(uv,a,.055),circle(uv,b,.055)));c=mix(c,vec3(.26,.27,.25),1.-smoothstep(-.005,.008,n));color=vec4(c,1.);}`;
function shader(gl,type,source){const s=gl.createShader(type);gl.shaderSource(s,source);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s));return s}
export function createSynapseRenderer(canvas){const gl=canvas.getContext("webgl2",{antialias:true});if(!gl)throw Error("WebGL2 is unavailable. The numeric experiment remains usable below.");const program=gl.createProgram();gl.attachShader(program,shader(gl,gl.VERTEX_SHADER,VERTEX));gl.attachShader(program,shader(gl,gl.FRAGMENT_SHADER,FRAGMENT));gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(program));const buffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([-1,-1,3,-1,-1,3]),gl.STATIC_DRAW);const loc=gl.getAttribLocation(program,"p");gl.enableVertexAttribArray(loc);gl.vertexAttribPointer(loc,2,gl.FLOAT,false,0,0);const uniforms={resolution:gl.getUniformLocation(program,"resolution"),left:gl.getUniformLocation(program,"leftStrength"),right:gl.getUniformLocation(program,"rightStrength")};let state={memoryStrength:0,interference:0};function draw(){const d=Math.min(devicePixelRatio||1,2),w=Math.max(1,Math.round(canvas.clientWidth*d)),h=Math.max(1,Math.round(canvas.clientHeight*d));if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h}gl.viewport(0,0,w,h);gl.useProgram(program);gl.uniform2f(uniforms.resolution,w,h);gl.uniform1f(uniforms.left,state.memoryStrength);gl.uniform1f(uniforms.right,state.interference);gl.drawArrays(gl.TRIANGLES,0,3)}new ResizeObserver(draw).observe(canvas);draw();return{update(next){state=next;draw()}}}

